version: 2

models:
  - name: fct_orders
    description: "Fact table: one row per order item (e.g., 1 order with 3 products = 3 rows)."
    columns:
      - name: order_item_key
        tests: [unique, not_null]
      - name: customer_sk
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_customers')
                field: customer_sk
      - name: product_sk
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_products')
                field: product_sk
      - name: organization_sk
        tests:
          - relationships:
              arguments:
                to: ref('dim_organizations')
                field: organization_sk
      - name: order_date
        tests: [not_null]
      - name: quantity
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 1
                max_value: 1000
      - name: amount
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 1
                max_value: 1000