envquery:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: dotted-hulling-477021-d2
      dataset: raw_staging         # ← your dev models
      threads: 4
      location: EU

    raw:  # ← new target for seeds
      type: bigquery
      method: oauth
      project: dotted-hulling-477021-d2
      dataset: raw_staging           # ← seeds land here
      threads: 1
      location: EU