envquery:
  outputs:
    dev:
      dataset: dbt_test
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: EU
      method: oauth
      priority: interactive
      project: dotted-hulling-477021-d2
      threads: 4
      type: bigquery
  target: dev
