version: 2

models:
  - name: customer_cohorts
    description: "Customer retention cohorts by first order month."
    columns:
      - name: cohort_month
        tests: [not_null]
      - name: months_since_cohort
        tests: [not_null]
      - name: active_customers
        tests: [not_null]
      - name: retention_rate_pct
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 0
                max_value: 100